/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ActionWorkflowJobsResponse;
import io.swagger.client.model.ActionWorkflowRunsResponse;
import io.swagger.client.model.Badge;
import io.swagger.client.model.CreateHookOption;
import io.swagger.client.model.CreateKeyOption;
import io.swagger.client.model.CreateOrgOption;
import io.swagger.client.model.CreateRepoOption;
import io.swagger.client.model.CreateUserOption;
import io.swagger.client.model.Cron;
import io.swagger.client.model.EditHookOption;
import io.swagger.client.model.EditUserOption;
import io.swagger.client.model.Email;
import io.swagger.client.model.Hook;
import io.swagger.client.model.Organization;
import io.swagger.client.model.PublicKey;
import io.swagger.client.model.RenameUserOption;
import io.swagger.client.model.Repository;
import io.swagger.client.model.User;
import io.swagger.client.model.UserBadgeOption;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminApi
 */
@Ignore
public class AdminApiTest {

    private final AdminApi api = new AdminApi();

    
    /**
     * Add a badge to a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminAddUserBadgesTest() throws Exception {
        String username = null;
        UserBadgeOption body = null;
        api.adminAddUserBadges(username, body);

        // TODO: test validations
    }
    
    /**
     * Adopt unadopted files as a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminAdoptRepositoryTest() throws Exception {
        String owner = null;
        String repo = null;
        api.adminAdoptRepository(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Create a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCreateHookTest() throws Exception {
        CreateHookOption body = null;
        Hook response = api.adminCreateHook(body);

        // TODO: test validations
    }
    
    /**
     * Create an organization
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCreateOrgTest() throws Exception {
        String username = null;
        CreateOrgOption organization = null;
        Organization response = api.adminCreateOrg(username, organization);

        // TODO: test validations
    }
    
    /**
     * Add a public key on behalf of a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCreatePublicKeyTest() throws Exception {
        String username = null;
        CreateKeyOption key = null;
        PublicKey response = api.adminCreatePublicKey(username, key);

        // TODO: test validations
    }
    
    /**
     * Create a repository on behalf of a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCreateRepoTest() throws Exception {
        String username = null;
        CreateRepoOption repository = null;
        Repository response = api.adminCreateRepo(username, repository);

        // TODO: test validations
    }
    
    /**
     * Get an global actions runner registration token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCreateRunnerRegistrationTokenTest() throws Exception {
        api.adminCreateRunnerRegistrationToken();

        // TODO: test validations
    }
    
    /**
     * Create a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCreateUserTest() throws Exception {
        CreateUserOption body = null;
        User response = api.adminCreateUser(body);

        // TODO: test validations
    }
    
    /**
     * List cron tasks
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCronListTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Cron> response = api.adminCronList(page, limit);

        // TODO: test validations
    }
    
    /**
     * Run cron task
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminCronRunTest() throws Exception {
        String task = null;
        api.adminCronRun(task);

        // TODO: test validations
    }
    
    /**
     * Delete a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminDeleteHookTest() throws Exception {
        Long id = null;
        api.adminDeleteHook(id);

        // TODO: test validations
    }
    
    /**
     * Delete unadopted files
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminDeleteUnadoptedRepositoryTest() throws Exception {
        String owner = null;
        String repo = null;
        api.adminDeleteUnadoptedRepository(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Delete a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminDeleteUserTest() throws Exception {
        String username = null;
        Boolean purge = null;
        api.adminDeleteUser(username, purge);

        // TODO: test validations
    }
    
    /**
     * Remove a badge from a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminDeleteUserBadgesTest() throws Exception {
        String username = null;
        UserBadgeOption body = null;
        api.adminDeleteUserBadges(username, body);

        // TODO: test validations
    }
    
    /**
     * Delete a user&#39;s public key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminDeleteUserPublicKeyTest() throws Exception {
        String username = null;
        Long id = null;
        api.adminDeleteUserPublicKey(username, id);

        // TODO: test validations
    }
    
    /**
     * Update a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminEditHookTest() throws Exception {
        Long id = null;
        EditHookOption body = null;
        Hook response = api.adminEditHook(id, body);

        // TODO: test validations
    }
    
    /**
     * Edit an existing user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminEditUserTest() throws Exception {
        String username = null;
        EditUserOption body = null;
        User response = api.adminEditUser(username, body);

        // TODO: test validations
    }
    
    /**
     * List all emails
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminGetAllEmailsTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Email> response = api.adminGetAllEmails(page, limit);

        // TODO: test validations
    }
    
    /**
     * List all organizations
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminGetAllOrgsTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Organization> response = api.adminGetAllOrgs(page, limit);

        // TODO: test validations
    }
    
    /**
     * Get a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminGetHookTest() throws Exception {
        Long id = null;
        Hook response = api.adminGetHook(id);

        // TODO: test validations
    }
    
    /**
     * Get an global actions runner registration token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminGetRunnerRegistrationTokenTest() throws Exception {
        api.adminGetRunnerRegistrationToken();

        // TODO: test validations
    }
    
    /**
     * List system&#39;s webhooks
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminListHooksTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        String type = null;
        List<Hook> response = api.adminListHooks(page, limit, type);

        // TODO: test validations
    }
    
    /**
     * List a user&#39;s badges
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminListUserBadgesTest() throws Exception {
        String username = null;
        List<Badge> response = api.adminListUserBadges(username);

        // TODO: test validations
    }
    
    /**
     * Rename a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminRenameUserTest() throws Exception {
        String username = null;
        RenameUserOption body = null;
        api.adminRenameUser(username, body);

        // TODO: test validations
    }
    
    /**
     * Search all emails
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminSearchEmailsTest() throws Exception {
        String q = null;
        Integer page = null;
        Integer limit = null;
        List<Email> response = api.adminSearchEmails(q, page, limit);

        // TODO: test validations
    }
    
    /**
     * Search users according filter conditions
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminSearchUsersTest() throws Exception {
        Long sourceId = null;
        String loginName = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.adminSearchUsers(sourceId, loginName, page, limit);

        // TODO: test validations
    }
    
    /**
     * List unadopted repositories
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void adminUnadoptedListTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        String pattern = null;
        List<String> response = api.adminUnadoptedList(page, limit, pattern);

        // TODO: test validations
    }
    
    /**
     * Delete an global runner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAdminRunnerTest() throws Exception {
        String runnerId = null;
        api.deleteAdminRunner(runnerId);

        // TODO: test validations
    }
    
    /**
     * Get an global runner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAdminRunnerTest() throws Exception {
        String runnerId = null;
        api.getAdminRunner(runnerId);

        // TODO: test validations
    }
    
    /**
     * Get all runners
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAdminRunnersTest() throws Exception {
        api.getAdminRunners();

        // TODO: test validations
    }
    
    /**
     * Lists all jobs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAdminWorkflowJobsTest() throws Exception {
        String status = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowJobsResponse response = api.listAdminWorkflowJobs(status, page, limit);

        // TODO: test validations
    }
    
    /**
     * Lists all runs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listAdminWorkflowRunsTest() throws Exception {
        String event = null;
        String branch = null;
        String status = null;
        String actor = null;
        String headSha = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowRunsResponse response = api.listAdminWorkflowRuns(event, branch, status, actor, headSha, page, limit);

        // TODO: test validations
    }
    
}
