/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.APIError;
import io.swagger.client.model.ActionArtifact;
import io.swagger.client.model.ActionArtifactsResponse;
import io.swagger.client.model.ActionTaskResponse;
import io.swagger.client.model.ActionVariable;
import io.swagger.client.model.ActionWorkflow;
import io.swagger.client.model.ActionWorkflowJob;
import io.swagger.client.model.ActionWorkflowJobsResponse;
import io.swagger.client.model.ActionWorkflowResponse;
import io.swagger.client.model.ActionWorkflowRun;
import io.swagger.client.model.ActionWorkflowRunsResponse;
import io.swagger.client.model.Activity;
import io.swagger.client.model.AddCollaboratorOption;
import io.swagger.client.model.AnnotatedTag;
import io.swagger.client.model.ApplyDiffPatchFileOptions;
import io.swagger.client.model.Attachment;
import io.swagger.client.model.Branch;
import io.swagger.client.model.BranchProtection;
import io.swagger.client.model.ChangeFilesOptions;
import io.swagger.client.model.ChangedFile;
import io.swagger.client.model.CombinedStatus;
import io.swagger.client.model.Commit;
import io.swagger.client.model.CommitStatus;
import io.swagger.client.model.Compare;
import io.swagger.client.model.ContentsExtResponse;
import io.swagger.client.model.ContentsResponse;
import io.swagger.client.model.CreateActionWorkflowDispatch;
import io.swagger.client.model.CreateBranchProtectionOption;
import io.swagger.client.model.CreateBranchRepoOption;
import io.swagger.client.model.CreateFileOptions;
import io.swagger.client.model.CreateForkOption;
import io.swagger.client.model.CreateHookOption;
import io.swagger.client.model.CreateKeyOption;
import io.swagger.client.model.CreateOrUpdateSecretOption;
import io.swagger.client.model.CreatePullRequestOption;
import io.swagger.client.model.CreatePullReviewOptions;
import io.swagger.client.model.CreatePushMirrorOption;
import io.swagger.client.model.CreateReleaseOption;
import io.swagger.client.model.CreateRepoOption;
import io.swagger.client.model.CreateStatusOption;
import io.swagger.client.model.CreateTagOption;
import io.swagger.client.model.CreateTagProtectionOption;
import io.swagger.client.model.CreateVariableOption;
import io.swagger.client.model.CreateWikiPageOptions;
import io.swagger.client.model.DeleteFileOptions;
import io.swagger.client.model.DeployKey;
import io.swagger.client.model.DismissPullReviewOptions;
import io.swagger.client.model.EditAttachmentOptions;
import io.swagger.client.model.EditBranchProtectionOption;
import io.swagger.client.model.EditGitHookOption;
import io.swagger.client.model.EditHookOption;
import io.swagger.client.model.EditPullRequestOption;
import io.swagger.client.model.EditReleaseOption;
import io.swagger.client.model.EditRepoOption;
import io.swagger.client.model.EditTagProtectionOption;
import java.io.File;
import io.swagger.client.model.FileDeleteResponse;
import io.swagger.client.model.FileResponse;
import io.swagger.client.model.FilesResponse;
import io.swagger.client.model.GenerateRepoOption;
import io.swagger.client.model.GetFilesOptions;
import io.swagger.client.model.GitBlobResponse;
import io.swagger.client.model.GitHook;
import io.swagger.client.model.GitTreeResponse;
import io.swagger.client.model.Hook;
import io.swagger.client.model.Issue;
import io.swagger.client.model.IssueConfig;
import io.swagger.client.model.IssueConfigValidation;
import io.swagger.client.model.IssueTemplate;
import org.threeten.bp.LocalDate;
import io.swagger.client.model.MergePullRequestOption;
import io.swagger.client.model.MergeUpstreamRequest;
import io.swagger.client.model.MergeUpstreamResponse;
import io.swagger.client.model.MigrateRepoOptions;
import io.swagger.client.model.NewIssuePinsAllowed;
import io.swagger.client.model.Note;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.PullRequest;
import io.swagger.client.model.PullReview;
import io.swagger.client.model.PullReviewComment;
import io.swagger.client.model.PullReviewRequestOptions;
import io.swagger.client.model.PushMirror;
import io.swagger.client.model.Reference;
import io.swagger.client.model.Release;
import io.swagger.client.model.RenameBranchRepoOption;
import io.swagger.client.model.RepoCollaboratorPermission;
import io.swagger.client.model.RepoTopicOptions;
import io.swagger.client.model.Repository;
import io.swagger.client.model.SearchResults;
import io.swagger.client.model.Secret;
import io.swagger.client.model.SubmitPullReviewOptions;
import io.swagger.client.model.Tag;
import io.swagger.client.model.TagProtection;
import io.swagger.client.model.Team;
import io.swagger.client.model.TopicName;
import io.swagger.client.model.TopicResponse;
import io.swagger.client.model.TrackedTime;
import io.swagger.client.model.TransferRepoOption;
import io.swagger.client.model.UpdateBranchProtectionPriories;
import io.swagger.client.model.UpdateFileOptions;
import io.swagger.client.model.UpdateRepoAvatarOption;
import io.swagger.client.model.UpdateVariableOption;
import io.swagger.client.model.User;
import io.swagger.client.model.WatchInfo;
import io.swagger.client.model.WikiCommitList;
import io.swagger.client.model.WikiPage;
import io.swagger.client.model.WikiPageMetaData;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RepositoryApi
 */
@Ignore
public class RepositoryApiTest {

    private final RepositoryApi api = new RepositoryApi();

    
    /**
     * Accept a repo transfer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void acceptRepoTransferTest() throws Exception {
        String owner = null;
        String repo = null;
        Repository response = api.acceptRepoTransfer(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Disable a workflow
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void actionsDisableWorkflowTest() throws Exception {
        String owner = null;
        String repo = null;
        String workflowId = null;
        api.actionsDisableWorkflow(owner, repo, workflowId);

        // TODO: test validations
    }
    
    /**
     * Create a workflow dispatch event
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void actionsDispatchWorkflowTest() throws Exception {
        String owner = null;
        String repo = null;
        String workflowId = null;
        CreateActionWorkflowDispatch body = null;
        api.actionsDispatchWorkflow(owner, repo, workflowId, body);

        // TODO: test validations
    }
    
    /**
     * Enable a workflow
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void actionsEnableWorkflowTest() throws Exception {
        String owner = null;
        String repo = null;
        String workflowId = null;
        api.actionsEnableWorkflow(owner, repo, workflowId);

        // TODO: test validations
    }
    
    /**
     * Get a workflow
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void actionsGetWorkflowTest() throws Exception {
        String owner = null;
        String repo = null;
        String workflowId = null;
        ActionWorkflow response = api.actionsGetWorkflow(owner, repo, workflowId);

        // TODO: test validations
    }
    
    /**
     * List repository workflows
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void actionsListRepositoryWorkflowsTest() throws Exception {
        String owner = null;
        String repo = null;
        ActionWorkflowResponse response = api.actionsListRepositoryWorkflows(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Create a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCurrentUserRepoTest() throws Exception {
        CreateRepoOption body = null;
        Repository response = api.createCurrentUserRepo(body);

        // TODO: test validations
    }
    
    /**
     * Fork a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createForkTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateForkOption body = null;
        Repository response = api.createFork(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a repo-level variable
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createRepoVariableTest() throws Exception {
        String owner = null;
        String repo = null;
        String variablename = null;
        CreateVariableOption body = null;
        api.createRepoVariable(owner, repo, variablename, body);

        // TODO: test validations
    }
    
    /**
     * Delete a workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteActionRunTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer run = null;
        api.deleteActionRun(owner, repo, run);

        // TODO: test validations
    }
    
    /**
     * Deletes a specific artifact for a workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteArtifactTest() throws Exception {
        String owner = null;
        String repo = null;
        String artifactId = null;
        api.deleteArtifact(owner, repo, artifactId);

        // TODO: test validations
    }
    
    /**
     * Delete an repo-level runner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRepoRunnerTest() throws Exception {
        String owner = null;
        String repo = null;
        String runnerId = null;
        api.deleteRepoRunner(owner, repo, runnerId);

        // TODO: test validations
    }
    
    /**
     * Delete a secret in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRepoSecretTest() throws Exception {
        String owner = null;
        String repo = null;
        String secretname = null;
        api.deleteRepoSecret(owner, repo, secretname);

        // TODO: test validations
    }
    
    /**
     * Delete a repo-level variable
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRepoVariableTest() throws Exception {
        String owner = null;
        String repo = null;
        String variablename = null;
        ActionVariable response = api.deleteRepoVariable(owner, repo, variablename);

        // TODO: test validations
    }
    
    /**
     * Downloads the job logs for a workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadActionsRunJobLogsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer jobId = null;
        api.downloadActionsRunJobLogs(owner, repo, jobId);

        // TODO: test validations
    }
    
    /**
     * Downloads a specific artifact for a workflow run redirects to blob url
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadArtifactTest() throws Exception {
        String owner = null;
        String repo = null;
        String artifactId = null;
        api.downloadArtifact(owner, repo, artifactId);

        // TODO: test validations
    }
    
    /**
     * Create a repository using a template
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void generateRepoTest() throws Exception {
        String templateOwner = null;
        String templateRepo = null;
        GenerateRepoOption body = null;
        Repository response = api.generateRepo(templateOwner, templateRepo, body);

        // TODO: test validations
    }
    
    /**
     * Gets the tag object of an annotated tag (not lightweight tags)
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAnnotatedTagTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        AnnotatedTag response = api.getAnnotatedTag(owner, repo, sha);

        // TODO: test validations
    }
    
    /**
     * Gets a specific artifact for a workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getArtifactTest() throws Exception {
        String owner = null;
        String repo = null;
        String artifactId = null;
        ActionArtifact response = api.getArtifact(owner, repo, artifactId);

        // TODO: test validations
    }
    
    /**
     * Lists all artifacts for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getArtifactsTest() throws Exception {
        String owner = null;
        String repo = null;
        String name = null;
        ActionArtifactsResponse response = api.getArtifacts(owner, repo, name);

        // TODO: test validations
    }
    
    /**
     * Lists all artifacts for a repository run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getArtifactsOfRunTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer run = null;
        String name = null;
        ActionArtifactsResponse response = api.getArtifactsOfRun(owner, repo, run, name);

        // TODO: test validations
    }
    
    /**
     * Gets the blob of a repository.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBlobTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        GitBlobResponse response = api.getBlob(owner, repo, sha);

        // TODO: test validations
    }
    
    /**
     * Get an repo-level runner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRepoRunnerTest() throws Exception {
        String owner = null;
        String repo = null;
        String runnerId = null;
        api.getRepoRunner(owner, repo, runnerId);

        // TODO: test validations
    }
    
    /**
     * Get repo-level runners
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRepoRunnersTest() throws Exception {
        String owner = null;
        String repo = null;
        api.getRepoRunners(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a repo-level variable
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRepoVariableTest() throws Exception {
        String owner = null;
        String repo = null;
        String variablename = null;
        ActionVariable response = api.getRepoVariable(owner, repo, variablename);

        // TODO: test validations
    }
    
    /**
     * Get repo-level variables list
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRepoVariablesListTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<ActionVariable> response = api.getRepoVariablesList(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * Gets the tree of a repository.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTreeTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        Boolean recursive = null;
        Integer page = null;
        Integer perPage = null;
        GitTreeResponse response = api.getTree(owner, repo, sha, recursive, page, perPage);

        // TODO: test validations
    }
    
    /**
     * Gets a specific workflow job for a workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWorkflowJobTest() throws Exception {
        String owner = null;
        String repo = null;
        String jobId = null;
        ActionWorkflowJob response = api.getWorkflowJob(owner, repo, jobId);

        // TODO: test validations
    }
    
    /**
     * Gets a specific workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWorkflowRunTest() throws Exception {
        String owner = null;
        String repo = null;
        String run = null;
        ActionWorkflowRun response = api.getWorkflowRun(owner, repo, run);

        // TODO: test validations
    }
    
    /**
     * Lists all runs for a repository run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getWorkflowRunsTest() throws Exception {
        String owner = null;
        String repo = null;
        String event = null;
        String branch = null;
        String status = null;
        String actor = null;
        String headSha = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowRunsResponse response = api.getWorkflowRuns(owner, repo, event, branch, status, actor, headSha, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s action tasks
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listActionTasksTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        ActionTaskResponse response = api.listActionTasks(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s forks
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listForksTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.listForks(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * Lists all jobs for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listWorkflowJobsTest() throws Exception {
        String owner = null;
        String repo = null;
        String status = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowJobsResponse response = api.listWorkflowJobs(owner, repo, status, page, limit);

        // TODO: test validations
    }
    
    /**
     * Lists all jobs for a workflow run
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listWorkflowRunJobsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer run = null;
        String status = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowJobsResponse response = api.listWorkflowRunJobs(owner, repo, run, status, page, limit);

        // TODO: test validations
    }
    
    /**
     * Reject a repo transfer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void rejectRepoTransferTest() throws Exception {
        String owner = null;
        String repo = null;
        Repository response = api.rejectRepoTransfer(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Add or Update a collaborator to a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoAddCollaboratorTest() throws Exception {
        String owner = null;
        String repo = null;
        String collaborator = null;
        AddCollaboratorOption body = null;
        api.repoAddCollaborator(owner, repo, collaborator, body);

        // TODO: test validations
    }
    
    /**
     * add a push mirror to the repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoAddPushMirrorTest() throws Exception {
        String owner = null;
        String repo = null;
        CreatePushMirrorOption body = null;
        PushMirror response = api.repoAddPushMirror(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Add a team to a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoAddTeamTest() throws Exception {
        String owner = null;
        String repo = null;
        String team = null;
        api.repoAddTeam(owner, repo, team);

        // TODO: test validations
    }
    
    /**
     * Add a topic to a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoAddTopicTest() throws Exception {
        String owner = null;
        String repo = null;
        String topic = null;
        api.repoAddTopic(owner, repo, topic);

        // TODO: test validations
    }
    
    /**
     * Apply diff patch to repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoApplyDiffPatchTest() throws Exception {
        String owner = null;
        String repo = null;
        ApplyDiffPatchFileOptions body = null;
        FileResponse response = api.repoApplyDiffPatch(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Cancel the scheduled auto merge for the given pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCancelScheduledAutoMergeTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        api.repoCancelScheduledAutoMerge(owner, repo, index);

        // TODO: test validations
    }
    
    /**
     * Modify multiple files in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoChangeFilesTest() throws Exception {
        String owner = null;
        String repo = null;
        ChangeFilesOptions body = null;
        FilesResponse response = api.repoChangeFiles(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Check if a user is a collaborator of a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCheckCollaboratorTest() throws Exception {
        String owner = null;
        String repo = null;
        String collaborator = null;
        api.repoCheckCollaborator(owner, repo, collaborator);

        // TODO: test validations
    }
    
    /**
     * Check if a team is assigned to a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCheckTeamTest() throws Exception {
        String owner = null;
        String repo = null;
        String team = null;
        Team response = api.repoCheckTeam(owner, repo, team);

        // TODO: test validations
    }
    
    /**
     * Get commit comparison information
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCompareDiffTest() throws Exception {
        String owner = null;
        String repo = null;
        String basehead = null;
        Compare response = api.repoCompareDiff(owner, repo, basehead);

        // TODO: test validations
    }
    
    /**
     * Create a branch
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateBranchTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateBranchRepoOption body = null;
        Branch response = api.repoCreateBranch(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a branch protections for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateBranchProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateBranchProtectionOption body = null;
        BranchProtection response = api.repoCreateBranchProtection(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a file in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateFileTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        CreateFileOptions body = null;
        FileResponse response = api.repoCreateFile(owner, repo, filepath, body);

        // TODO: test validations
    }
    
    /**
     * Create a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateHookTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateHookOption body = null;
        Hook response = api.repoCreateHook(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Add a key to a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateKeyTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateKeyOption body = null;
        DeployKey response = api.repoCreateKey(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreatePullRequestTest() throws Exception {
        String owner = null;
        String repo = null;
        CreatePullRequestOption body = null;
        PullRequest response = api.repoCreatePullRequest(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a review to an pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreatePullReviewTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        CreatePullReviewOptions body = null;
        PullReview response = api.repoCreatePullReview(owner, repo, index, body);

        // TODO: test validations
    }
    
    /**
     * create review requests for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreatePullReviewRequestsTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        PullReviewRequestOptions body = null;
        List<PullReview> response = api.repoCreatePullReviewRequests(owner, repo, index, body);

        // TODO: test validations
    }
    
    /**
     * Create a release
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateReleaseTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateReleaseOption body = null;
        Release response = api.repoCreateRelease(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a release attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateReleaseAttachmentTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        String name = null;
        File attachment = null;
        Attachment response = api.repoCreateReleaseAttachment(owner, repo, id, name, attachment);

        // TODO: test validations
    }
    
    /**
     * Get a repository&#39;s actions runner registration token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateRunnerRegistrationTokenTest() throws Exception {
        String owner = null;
        String repo = null;
        api.repoCreateRunnerRegistrationToken(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Create a commit status
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateStatusTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        CreateStatusOption body = null;
        CommitStatus response = api.repoCreateStatus(owner, repo, sha, body);

        // TODO: test validations
    }
    
    /**
     * Create a new git tag in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateTagTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateTagOption body = null;
        Tag response = api.repoCreateTag(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a tag protections for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateTagProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateTagProtectionOption body = null;
        TagProtection response = api.repoCreateTagProtection(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Create a wiki page
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoCreateWikiPageTest() throws Exception {
        String owner = null;
        String repo = null;
        CreateWikiPageOptions body = null;
        WikiPage response = api.repoCreateWikiPage(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Delete a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteTest() throws Exception {
        String owner = null;
        String repo = null;
        api.repoDelete(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Delete avatar
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteAvatarTest() throws Exception {
        String owner = null;
        String repo = null;
        api.repoDeleteAvatar(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Delete a specific branch from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteBranchTest() throws Exception {
        String owner = null;
        String repo = null;
        String branch = null;
        api.repoDeleteBranch(owner, repo, branch);

        // TODO: test validations
    }
    
    /**
     * Delete a specific branch protection for the repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteBranchProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        String name = null;
        api.repoDeleteBranchProtection(owner, repo, name);

        // TODO: test validations
    }
    
    /**
     * Delete a collaborator from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteCollaboratorTest() throws Exception {
        String owner = null;
        String repo = null;
        String collaborator = null;
        api.repoDeleteCollaborator(owner, repo, collaborator);

        // TODO: test validations
    }
    
    /**
     * Delete a file in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteFileTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        DeleteFileOptions body = null;
        FileDeleteResponse response = api.repoDeleteFile(owner, repo, filepath, body);

        // TODO: test validations
    }
    
    /**
     * Delete a Git hook in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteGitHookTest() throws Exception {
        String owner = null;
        String repo = null;
        String id = null;
        api.repoDeleteGitHook(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Delete a hook in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteHookTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        api.repoDeleteHook(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Delete a key from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteKeyTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        api.repoDeleteKey(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Delete a specific review from a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeletePullReviewTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Long id = null;
        api.repoDeletePullReview(owner, repo, index, id);

        // TODO: test validations
    }
    
    /**
     * cancel review requests for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeletePullReviewRequestsTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        PullReviewRequestOptions body = null;
        api.repoDeletePullReviewRequests(owner, repo, index, body);

        // TODO: test validations
    }
    
    /**
     * deletes a push mirror from a repository by remoteName
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeletePushMirrorTest() throws Exception {
        String owner = null;
        String repo = null;
        String name = null;
        api.repoDeletePushMirror(owner, repo, name);

        // TODO: test validations
    }
    
    /**
     * Delete a release
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteReleaseTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        api.repoDeleteRelease(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Delete a release attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteReleaseAttachmentTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        Long attachmentId = null;
        api.repoDeleteReleaseAttachment(owner, repo, id, attachmentId);

        // TODO: test validations
    }
    
    /**
     * Delete a release by tag name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteReleaseByTagTest() throws Exception {
        String owner = null;
        String repo = null;
        String tag = null;
        api.repoDeleteReleaseByTag(owner, repo, tag);

        // TODO: test validations
    }
    
    /**
     * Delete a repository&#39;s tag by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteTagTest() throws Exception {
        String owner = null;
        String repo = null;
        String tag = null;
        api.repoDeleteTag(owner, repo, tag);

        // TODO: test validations
    }
    
    /**
     * Delete a specific tag protection for the repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteTagProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer id = null;
        api.repoDeleteTagProtection(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Delete a team from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteTeamTest() throws Exception {
        String owner = null;
        String repo = null;
        String team = null;
        api.repoDeleteTeam(owner, repo, team);

        // TODO: test validations
    }
    
    /**
     * Delete a topic from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteTopicTest() throws Exception {
        String owner = null;
        String repo = null;
        String topic = null;
        api.repoDeleteTopic(owner, repo, topic);

        // TODO: test validations
    }
    
    /**
     * Delete a wiki page
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDeleteWikiPageTest() throws Exception {
        String owner = null;
        String repo = null;
        String pageName = null;
        api.repoDeleteWikiPage(owner, repo, pageName);

        // TODO: test validations
    }
    
    /**
     * Dismiss a review for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDismissPullReviewTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Long id = null;
        DismissPullReviewOptions body = null;
        PullReview response = api.repoDismissPullReview(owner, repo, index, id, body);

        // TODO: test validations
    }
    
    /**
     * Get a commit&#39;s diff or patch
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDownloadCommitDiffOrPatchTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        String diffType = null;
        String response = api.repoDownloadCommitDiffOrPatch(owner, repo, sha, diffType);

        // TODO: test validations
    }
    
    /**
     * Get a pull request diff or patch
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoDownloadPullDiffOrPatchTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        String diffType = null;
        Boolean binary = null;
        String response = api.repoDownloadPullDiffOrPatch(owner, repo, index, diffType, binary);

        // TODO: test validations
    }
    
    /**
     * Edit a repository&#39;s properties. Only fields that are set will be changed.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditTest() throws Exception {
        String owner = null;
        String repo = null;
        EditRepoOption body = null;
        Repository response = api.repoEdit(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Edit a branch protections for a repository. Only fields that are set will be changed
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditBranchProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        String name = null;
        EditBranchProtectionOption body = null;
        BranchProtection response = api.repoEditBranchProtection(owner, repo, name, body);

        // TODO: test validations
    }
    
    /**
     * Edit a Git hook in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditGitHookTest() throws Exception {
        String owner = null;
        String repo = null;
        String id = null;
        EditGitHookOption body = null;
        GitHook response = api.repoEditGitHook(owner, repo, id, body);

        // TODO: test validations
    }
    
    /**
     * Edit a hook in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditHookTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        EditHookOption body = null;
        Hook response = api.repoEditHook(owner, repo, id, body);

        // TODO: test validations
    }
    
    /**
     * Update a pull request. If using deadline only the date will be taken into account, and time of day ignored.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditPullRequestTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        EditPullRequestOption body = null;
        PullRequest response = api.repoEditPullRequest(owner, repo, index, body);

        // TODO: test validations
    }
    
    /**
     * Update a release
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditReleaseTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        EditReleaseOption body = null;
        Release response = api.repoEditRelease(owner, repo, id, body);

        // TODO: test validations
    }
    
    /**
     * Edit a release attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditReleaseAttachmentTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        Long attachmentId = null;
        EditAttachmentOptions body = null;
        Attachment response = api.repoEditReleaseAttachment(owner, repo, id, attachmentId, body);

        // TODO: test validations
    }
    
    /**
     * Edit a tag protections for a repository. Only fields that are set will be changed
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditTagProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer id = null;
        EditTagProtectionOption body = null;
        TagProtection response = api.repoEditTagProtection(owner, repo, id, body);

        // TODO: test validations
    }
    
    /**
     * Edit a wiki page
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoEditWikiPageTest() throws Exception {
        String owner = null;
        String repo = null;
        String pageName = null;
        CreateWikiPageOptions body = null;
        WikiPage response = api.repoEditWikiPage(owner, repo, pageName, body);

        // TODO: test validations
    }
    
    /**
     * Get a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetTest() throws Exception {
        String owner = null;
        String repo = null;
        Repository response = api.repoGet(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a list of all commits from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetAllCommitsTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        String path = null;
        OffsetDateTime since = null;
        OffsetDateTime until = null;
        Boolean stat = null;
        Boolean verification = null;
        Boolean files = null;
        Integer page = null;
        Integer limit = null;
        String not = null;
        List<Commit> response = api.repoGetAllCommits(owner, repo, sha, path, since, until, stat, verification, files, page, limit, not);

        // TODO: test validations
    }
    
    /**
     * Get an archive of a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetArchiveTest() throws Exception {
        String owner = null;
        String repo = null;
        String archive = null;
        api.repoGetArchive(owner, repo, archive);

        // TODO: test validations
    }
    
    /**
     * Return all users that have write access and can be assigned to issues
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetAssigneesTest() throws Exception {
        String owner = null;
        String repo = null;
        List<User> response = api.repoGetAssignees(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Retrieve a specific branch from a repository, including its effective branch protection
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetBranchTest() throws Exception {
        String owner = null;
        String repo = null;
        String branch = null;
        Branch response = api.repoGetBranch(owner, repo, branch);

        // TODO: test validations
    }
    
    /**
     * Get a specific branch protection for the repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetBranchProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        String name = null;
        BranchProtection response = api.repoGetBranchProtection(owner, repo, name);

        // TODO: test validations
    }
    
    /**
     * Get a repository by id
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetByIDTest() throws Exception {
        Long id = null;
        Repository response = api.repoGetByID(id);

        // TODO: test validations
    }
    
    /**
     * Get a commit&#39;s combined status, by branch/tag/commit reference
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetCombinedStatusByRefTest() throws Exception {
        String owner = null;
        String repo = null;
        String ref = null;
        Integer page = null;
        Integer limit = null;
        CombinedStatus response = api.repoGetCombinedStatusByRef(owner, repo, ref, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get the merged pull request of the commit
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetCommitPullRequestTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        PullRequest response = api.repoGetCommitPullRequest(owner, repo, sha);

        // TODO: test validations
    }
    
    /**
     * Gets the metadata and contents (if a file) of an entry in a repository, or a list of entries if a dir.
     *
     * This API follows GitHub&#39;s design, and it is not easy to use. Recommend users to use the \&quot;contents-ext\&quot; API instead.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetContentsTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        String ref = null;
        ContentsResponse response = api.repoGetContents(owner, repo, filepath, ref);

        // TODO: test validations
    }
    
    /**
     * The extended \&quot;contents\&quot; API, to get file metadata and/or content, or list a directory.
     *
     * It guarantees that only one of the response fields is set if the request succeeds. Users can pass \&quot;includes&#x3D;file_content\&quot; or \&quot;includes&#x3D;lfs_metadata\&quot; to retrieve more fields. \&quot;includes&#x3D;file_content\&quot; only works for single file, if you need to retrieve file contents in batch, use \&quot;file-contents\&quot; API after listing the directory.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetContentsExtTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        String ref = null;
        String includes = null;
        ContentsExtResponse response = api.repoGetContentsExt(owner, repo, filepath, ref, includes);

        // TODO: test validations
    }
    
    /**
     * Gets the metadata of all the entries of the root dir.
     *
     * This API follows GitHub&#39;s design, and it is not easy to use. Recommend users to use our \&quot;contents-ext\&quot; API instead.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetContentsListTest() throws Exception {
        String owner = null;
        String repo = null;
        String ref = null;
        List<ContentsResponse> response = api.repoGetContentsList(owner, repo, ref);

        // TODO: test validations
    }
    
    /**
     * Get the EditorConfig definitions of a file in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetEditorConfigTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        String ref = null;
        api.repoGetEditorConfig(owner, repo, filepath, ref);

        // TODO: test validations
    }
    
    /**
     * Get the metadata and contents of requested files
     *
     * See the POST method. This GET method supports using JSON encoded request body in query parameter.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetFileContentsTest() throws Exception {
        String owner = null;
        String repo = null;
        String body = null;
        String ref = null;
        List<ContentsResponse> response = api.repoGetFileContents(owner, repo, body, ref);

        // TODO: test validations
    }
    
    /**
     * Get the metadata and contents of requested files
     *
     * Uses automatic pagination based on default page size and max response size and returns the maximum allowed number of files. Files which could not be retrieved are null. Files which are too large are being returned with &#x60;encoding &#x3D;&#x3D; null&#x60;, &#x60;content &#x3D;&#x3D; null&#x60; and &#x60;size &gt; 0&#x60;, they can be requested separately by using the &#x60;download_url&#x60;.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetFileContentsPostTest() throws Exception {
        String owner = null;
        String repo = null;
        GetFilesOptions body = null;
        String ref = null;
        List<ContentsResponse> response = api.repoGetFileContentsPost(owner, repo, body, ref);

        // TODO: test validations
    }
    
    /**
     * Get a Git hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetGitHookTest() throws Exception {
        String owner = null;
        String repo = null;
        String id = null;
        GitHook response = api.repoGetGitHook(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Get a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetHookTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        Hook response = api.repoGetHook(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Returns the issue config for a repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetIssueConfigTest() throws Exception {
        String owner = null;
        String repo = null;
        IssueConfig response = api.repoGetIssueConfig(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get available issue templates for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetIssueTemplatesTest() throws Exception {
        String owner = null;
        String repo = null;
        List<IssueTemplate> response = api.repoGetIssueTemplates(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a repository&#39;s key by id
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetKeyTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        DeployKey response = api.repoGetKey(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Get languages and number of bytes of code written
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetLanguagesTest() throws Exception {
        String owner = null;
        String repo = null;
        Map<String, Long> response = api.repoGetLanguages(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Gets the most recent non-prerelease, non-draft release of a repository, sorted by created_at
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetLatestReleaseTest() throws Exception {
        String owner = null;
        String repo = null;
        Release response = api.repoGetLatestRelease(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get repo licenses
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetLicensesTest() throws Exception {
        String owner = null;
        String repo = null;
        List<String> response = api.repoGetLicenses(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a note corresponding to a single commit from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetNoteTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        Boolean verification = null;
        Boolean files = null;
        Note response = api.repoGetNote(owner, repo, sha, verification, files);

        // TODO: test validations
    }
    
    /**
     * Get a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPullRequestTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        PullRequest response = api.repoGetPullRequest(owner, repo, index);

        // TODO: test validations
    }
    
    /**
     * Get a pull request by base and head
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPullRequestByBaseHeadTest() throws Exception {
        String owner = null;
        String repo = null;
        String base = null;
        String head = null;
        PullRequest response = api.repoGetPullRequestByBaseHead(owner, repo, base, head);

        // TODO: test validations
    }
    
    /**
     * Get commits for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPullRequestCommitsTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Integer page = null;
        Integer limit = null;
        Boolean verification = null;
        Boolean files = null;
        List<Commit> response = api.repoGetPullRequestCommits(owner, repo, index, page, limit, verification, files);

        // TODO: test validations
    }
    
    /**
     * Get changed files for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPullRequestFilesTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        String skipTo = null;
        String whitespace = null;
        Integer page = null;
        Integer limit = null;
        List<ChangedFile> response = api.repoGetPullRequestFiles(owner, repo, index, skipTo, whitespace, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get a specific review for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPullReviewTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Long id = null;
        PullReview response = api.repoGetPullReview(owner, repo, index, id);

        // TODO: test validations
    }
    
    /**
     * Get a specific review for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPullReviewCommentsTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Long id = null;
        List<PullReviewComment> response = api.repoGetPullReviewComments(owner, repo, index, id);

        // TODO: test validations
    }
    
    /**
     * Get push mirror of the repository by remoteName
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetPushMirrorByRemoteNameTest() throws Exception {
        String owner = null;
        String repo = null;
        String name = null;
        PushMirror response = api.repoGetPushMirrorByRemoteName(owner, repo, name);

        // TODO: test validations
    }
    
    /**
     * Get a file from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetRawFileTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        String ref = null;
        File response = api.repoGetRawFile(owner, repo, filepath, ref);

        // TODO: test validations
    }
    
    /**
     * Get a file or it&#39;s LFS object from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetRawFileOrLFSTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        String ref = null;
        File response = api.repoGetRawFileOrLFS(owner, repo, filepath, ref);

        // TODO: test validations
    }
    
    /**
     * Get a release
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetReleaseTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        Release response = api.repoGetRelease(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Get a release attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetReleaseAttachmentTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        Long attachmentId = null;
        Attachment response = api.repoGetReleaseAttachment(owner, repo, id, attachmentId);

        // TODO: test validations
    }
    
    /**
     * Get a release by tag name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetReleaseByTagTest() throws Exception {
        String owner = null;
        String repo = null;
        String tag = null;
        Release response = api.repoGetReleaseByTag(owner, repo, tag);

        // TODO: test validations
    }
    
    /**
     * Get repository permissions for a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetRepoPermissionsTest() throws Exception {
        String owner = null;
        String repo = null;
        String collaborator = null;
        RepoCollaboratorPermission response = api.repoGetRepoPermissions(owner, repo, collaborator);

        // TODO: test validations
    }
    
    /**
     * Return all users that can be requested to review in this repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetReviewersTest() throws Exception {
        String owner = null;
        String repo = null;
        List<User> response = api.repoGetReviewers(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a repository&#39;s actions runner registration token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetRunnerRegistrationTokenTest() throws Exception {
        String owner = null;
        String repo = null;
        api.repoGetRunnerRegistrationToken(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a single commit from a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetSingleCommitTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        Boolean stat = null;
        Boolean verification = null;
        Boolean files = null;
        Commit response = api.repoGetSingleCommit(owner, repo, sha, stat, verification, files);

        // TODO: test validations
    }
    
    /**
     * Get the tag of a repository by tag name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetTagTest() throws Exception {
        String owner = null;
        String repo = null;
        String tag = null;
        Tag response = api.repoGetTag(owner, repo, tag);

        // TODO: test validations
    }
    
    /**
     * Get a specific tag protection for the repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetTagProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer id = null;
        TagProtection response = api.repoGetTagProtection(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * Get a wiki page
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetWikiPageTest() throws Exception {
        String owner = null;
        String repo = null;
        String pageName = null;
        WikiPage response = api.repoGetWikiPage(owner, repo, pageName);

        // TODO: test validations
    }
    
    /**
     * Get revisions of a wiki page
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetWikiPageRevisionsTest() throws Exception {
        String owner = null;
        String repo = null;
        String pageName = null;
        Integer page = null;
        WikiCommitList response = api.repoGetWikiPageRevisions(owner, repo, pageName, page);

        // TODO: test validations
    }
    
    /**
     * Get all wiki pages
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoGetWikiPagesTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<WikiPageMetaData> response = api.repoGetWikiPages(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List an repo&#39;s actions secrets
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListActionsSecretsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<Secret> response = api.repoListActionsSecrets(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s activity feeds
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListActivityFeedsTest() throws Exception {
        String owner = null;
        String repo = null;
        LocalDate date = null;
        Integer page = null;
        Integer limit = null;
        List<Activity> response = api.repoListActivityFeeds(owner, repo, date, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get specified ref or filtered repository&#39;s refs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListAllGitRefsTest() throws Exception {
        String owner = null;
        String repo = null;
        List<Reference> response = api.repoListAllGitRefs(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List branch protections for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListBranchProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        List<BranchProtection> response = api.repoListBranchProtection(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s branches
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListBranchesTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<Branch> response = api.repoListBranches(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s collaborators
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListCollaboratorsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.repoListCollaborators(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the Git hooks in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListGitHooksTest() throws Exception {
        String owner = null;
        String repo = null;
        List<GitHook> response = api.repoListGitHooks(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get specified ref or filtered repository&#39;s refs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListGitRefsTest() throws Exception {
        String owner = null;
        String repo = null;
        String ref = null;
        List<Reference> response = api.repoListGitRefs(owner, repo, ref);

        // TODO: test validations
    }
    
    /**
     * List the hooks in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListHooksTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<Hook> response = api.repoListHooks(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s keys
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListKeysTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer keyId = null;
        String fingerprint = null;
        Integer page = null;
        Integer limit = null;
        List<DeployKey> response = api.repoListKeys(owner, repo, keyId, fingerprint, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s pinned issues
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListPinnedIssuesTest() throws Exception {
        String owner = null;
        String repo = null;
        List<Issue> response = api.repoListPinnedIssues(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s pinned pull requests
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListPinnedPullRequestsTest() throws Exception {
        String owner = null;
        String repo = null;
        List<PullRequest> response = api.repoListPinnedPullRequests(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s pull requests
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListPullRequestsTest() throws Exception {
        String owner = null;
        String repo = null;
        String baseBranch = null;
        String state = null;
        String sort = null;
        Long milestone = null;
        List<Long> labels = null;
        String poster = null;
        Integer page = null;
        Integer limit = null;
        List<PullRequest> response = api.repoListPullRequests(owner, repo, baseBranch, state, sort, milestone, labels, poster, page, limit);

        // TODO: test validations
    }
    
    /**
     * List all reviews for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListPullReviewsTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Integer page = null;
        Integer limit = null;
        List<PullReview> response = api.repoListPullReviews(owner, repo, index, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get all push mirrors of the repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListPushMirrorsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<PushMirror> response = api.repoListPushMirrors(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List release&#39;s attachments
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListReleaseAttachmentsTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        List<Attachment> response = api.repoListReleaseAttachments(owner, repo, id);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s releases
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListReleasesTest() throws Exception {
        String owner = null;
        String repo = null;
        Boolean draft = null;
        Boolean preRelease = null;
        Integer page = null;
        Integer limit = null;
        List<Release> response = api.repoListReleases(owner, repo, draft, preRelease, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s stargazers
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListStargazersTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.repoListStargazers(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get a commit&#39;s statuses
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListStatusesTest() throws Exception {
        String owner = null;
        String repo = null;
        String sha = null;
        String sort = null;
        String state = null;
        Integer page = null;
        Integer limit = null;
        List<CommitStatus> response = api.repoListStatuses(owner, repo, sha, sort, state, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get a commit&#39;s statuses, by branch/tag/commit reference
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListStatusesByRefTest() throws Exception {
        String owner = null;
        String repo = null;
        String ref = null;
        String sort = null;
        String state = null;
        Integer page = null;
        Integer limit = null;
        List<CommitStatus> response = api.repoListStatusesByRef(owner, repo, ref, sort, state, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s watchers
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListSubscribersTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.repoListSubscribers(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List tag protections for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListTagProtectionTest() throws Exception {
        String owner = null;
        String repo = null;
        List<TagProtection> response = api.repoListTagProtection(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s tags
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListTagsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        List<Tag> response = api.repoListTags(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a repository&#39;s teams
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListTeamsTest() throws Exception {
        String owner = null;
        String repo = null;
        List<Team> response = api.repoListTeams(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get list of topics that a repository has
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoListTopicsTest() throws Exception {
        String owner = null;
        String repo = null;
        Integer page = null;
        Integer limit = null;
        TopicName response = api.repoListTopics(owner, repo, page, limit);

        // TODO: test validations
    }
    
    /**
     * Merge a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoMergePullRequestTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        MergePullRequestOption body = null;
        api.repoMergePullRequest(owner, repo, index, body);

        // TODO: test validations
    }
    
    /**
     * Merge a branch from upstream
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoMergeUpstreamTest() throws Exception {
        String owner = null;
        String repo = null;
        MergeUpstreamRequest body = null;
        MergeUpstreamResponse response = api.repoMergeUpstream(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Migrate a remote git repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoMigrateTest() throws Exception {
        MigrateRepoOptions body = null;
        Repository response = api.repoMigrate(body);

        // TODO: test validations
    }
    
    /**
     * Sync a mirrored repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoMirrorSyncTest() throws Exception {
        String owner = null;
        String repo = null;
        api.repoMirrorSync(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Returns if new Issue Pins are allowed
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoNewPinAllowedTest() throws Exception {
        String owner = null;
        String repo = null;
        NewIssuePinsAllowed response = api.repoNewPinAllowed(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Check if a pull request has been merged
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoPullRequestIsMergedTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        api.repoPullRequestIsMerged(owner, repo, index);

        // TODO: test validations
    }
    
    /**
     * Sync all push mirrored repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoPushMirrorSyncTest() throws Exception {
        String owner = null;
        String repo = null;
        api.repoPushMirrorSync(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Rename a branch
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoRenameBranchTest() throws Exception {
        String owner = null;
        String repo = null;
        String branch = null;
        RenameBranchRepoOption body = null;
        api.repoRenameBranch(owner, repo, branch, body);

        // TODO: test validations
    }
    
    /**
     * Search for repositories
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoSearchTest() throws Exception {
        String q = null;
        Boolean topic = null;
        Boolean includeDesc = null;
        Long uid = null;
        Long priorityOwnerId = null;
        Long teamId = null;
        Long starredBy = null;
        Boolean _private = null;
        Boolean isPrivate = null;
        Boolean template = null;
        Boolean archived = null;
        String mode = null;
        Boolean exclusive = null;
        String sort = null;
        String order = null;
        Integer page = null;
        Integer limit = null;
        SearchResults response = api.repoSearch(q, topic, includeDesc, uid, priorityOwnerId, teamId, starredBy, _private, isPrivate, template, archived, mode, exclusive, sort, order, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get signing-key.gpg for given repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoSigningKeyTest() throws Exception {
        String owner = null;
        String repo = null;
        String response = api.repoSigningKey(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get signing-key.pub for given repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoSigningKeySSHTest() throws Exception {
        String owner = null;
        String repo = null;
        String response = api.repoSigningKeySSH(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Submit a pending review to an pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoSubmitPullReviewTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Long id = null;
        SubmitPullReviewOptions body = null;
        PullReview response = api.repoSubmitPullReview(owner, repo, index, id, body);

        // TODO: test validations
    }
    
    /**
     * Test a push webhook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoTestHookTest() throws Exception {
        String owner = null;
        String repo = null;
        Long id = null;
        String ref = null;
        api.repoTestHook(owner, repo, id, ref);

        // TODO: test validations
    }
    
    /**
     * List a repo&#39;s tracked times
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoTrackedTimesTest() throws Exception {
        String owner = null;
        String repo = null;
        String user = null;
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer page = null;
        Integer limit = null;
        List<TrackedTime> response = api.repoTrackedTimes(owner, repo, user, since, before, page, limit);

        // TODO: test validations
    }
    
    /**
     * Transfer a repo ownership
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoTransferTest() throws Exception {
        String owner = null;
        String repo = null;
        TransferRepoOption body = null;
        Repository response = api.repoTransfer(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Cancel to dismiss a review for a pull request
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoUnDismissPullReviewTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        Long id = null;
        PullReview response = api.repoUnDismissPullReview(owner, repo, index, id);

        // TODO: test validations
    }
    
    /**
     * Update avatar
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoUpdateAvatarTest() throws Exception {
        String owner = null;
        String repo = null;
        UpdateRepoAvatarOption body = null;
        api.repoUpdateAvatar(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Update the priorities of branch protections for a repository.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoUpdateBranchProtectionPrioriesTest() throws Exception {
        String owner = null;
        String repo = null;
        UpdateBranchProtectionPriories body = null;
        api.repoUpdateBranchProtectionPriories(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Update a file in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoUpdateFileTest() throws Exception {
        String owner = null;
        String repo = null;
        String filepath = null;
        UpdateFileOptions body = null;
        FileResponse response = api.repoUpdateFile(owner, repo, filepath, body);

        // TODO: test validations
    }
    
    /**
     * Merge PR&#39;s baseBranch into headBranch
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoUpdatePullRequestTest() throws Exception {
        String owner = null;
        String repo = null;
        Long index = null;
        String style = null;
        api.repoUpdatePullRequest(owner, repo, index, style);

        // TODO: test validations
    }
    
    /**
     * Replace list of topics for a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoUpdateTopicsTest() throws Exception {
        String owner = null;
        String repo = null;
        RepoTopicOptions body = null;
        api.repoUpdateTopics(owner, repo, body);

        // TODO: test validations
    }
    
    /**
     * Returns the validation information for a issue config
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void repoValidateIssueConfigTest() throws Exception {
        String owner = null;
        String repo = null;
        IssueConfigValidation response = api.repoValidateIssueConfig(owner, repo);

        // TODO: test validations
    }
    
    /**
     * search topics via keyword
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void topicSearchTest() throws Exception {
        String q = null;
        Integer page = null;
        Integer limit = null;
        List<TopicResponse> response = api.topicSearch(q, page, limit);

        // TODO: test validations
    }
    
    /**
     * Create or Update a secret value in a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateRepoSecretTest() throws Exception {
        String owner = null;
        String repo = null;
        String secretname = null;
        CreateOrUpdateSecretOption body = null;
        api.updateRepoSecret(owner, repo, secretname, body);

        // TODO: test validations
    }
    
    /**
     * Update a repo-level variable
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateRepoVariableTest() throws Exception {
        String owner = null;
        String repo = null;
        String variablename = null;
        UpdateVariableOption body = null;
        api.updateRepoVariable(owner, repo, variablename, body);

        // TODO: test validations
    }
    
    /**
     * Check if the current user is watching a repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentCheckSubscriptionTest() throws Exception {
        String owner = null;
        String repo = null;
        WatchInfo response = api.userCurrentCheckSubscription(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Unwatch a repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentDeleteSubscriptionTest() throws Exception {
        String owner = null;
        String repo = null;
        api.userCurrentDeleteSubscription(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Watch a repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentPutSubscriptionTest() throws Exception {
        String owner = null;
        String repo = null;
        WatchInfo response = api.userCurrentPutSubscription(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List a user&#39;s tracked times in a repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userTrackedTimesTest() throws Exception {
        String owner = null;
        String repo = null;
        String user = null;
        List<TrackedTime> response = api.userTrackedTimes(owner, repo, user);

        // TODO: test validations
    }
    
}
