/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.GeneralAPISettings;
import io.swagger.client.model.GeneralAttachmentSettings;
import io.swagger.client.model.GeneralRepoSettings;
import io.swagger.client.model.GeneralUISettings;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SettingsApi
 */
@Ignore
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    
    /**
     * Get instance&#39;s global settings for api
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getGeneralAPISettingsTest() throws Exception {
        GeneralAPISettings response = api.getGeneralAPISettings();

        // TODO: test validations
    }
    
    /**
     * Get instance&#39;s global settings for Attachment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getGeneralAttachmentSettingsTest() throws Exception {
        GeneralAttachmentSettings response = api.getGeneralAttachmentSettings();

        // TODO: test validations
    }
    
    /**
     * Get instance&#39;s global settings for repositories
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getGeneralRepositorySettingsTest() throws Exception {
        GeneralRepoSettings response = api.getGeneralRepositorySettings();

        // TODO: test validations
    }
    
    /**
     * Get instance&#39;s global settings for ui
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getGeneralUISettingsTest() throws Exception {
        GeneralUISettings response = api.getGeneralUISettings();

        // TODO: test validations
    }
    
}
