/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.AccessToken;
import io.swagger.client.model.ActionVariable;
import io.swagger.client.model.ActionWorkflowJobsResponse;
import io.swagger.client.model.ActionWorkflowRunsResponse;
import io.swagger.client.model.Activity;
import io.swagger.client.model.CreateAccessTokenOption;
import io.swagger.client.model.CreateEmailOption;
import io.swagger.client.model.CreateGPGKeyOption;
import io.swagger.client.model.CreateHookOption;
import io.swagger.client.model.CreateKeyOption;
import io.swagger.client.model.CreateOAuth2ApplicationOptions;
import io.swagger.client.model.CreateOrUpdateSecretOption;
import io.swagger.client.model.CreateRepoOption;
import io.swagger.client.model.CreateVariableOption;
import io.swagger.client.model.DeleteEmailOption;
import io.swagger.client.model.EditHookOption;
import io.swagger.client.model.Email;
import io.swagger.client.model.GPGKey;
import io.swagger.client.model.Hook;
import io.swagger.client.model.InlineResponse2001;
import org.threeten.bp.LocalDate;
import io.swagger.client.model.OAuth2Application;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.PublicKey;
import io.swagger.client.model.Repository;
import io.swagger.client.model.StopWatch;
import io.swagger.client.model.Team;
import io.swagger.client.model.TrackedTime;
import io.swagger.client.model.UpdateUserAvatarOption;
import io.swagger.client.model.UpdateVariableOption;
import io.swagger.client.model.User;
import io.swagger.client.model.UserHeatmapData;
import io.swagger.client.model.UserSettings;
import io.swagger.client.model.UserSettingsOptions;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * Create a repository
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCurrentUserRepoTest() throws Exception {
        CreateRepoOption body = null;
        Repository response = api.createCurrentUserRepo(body);

        // TODO: test validations
    }
    
    /**
     * Create a user-level variable
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createUserVariableTest() throws Exception {
        String variablename = null;
        CreateVariableOption body = null;
        api.createUserVariable(variablename, body);

        // TODO: test validations
    }
    
    /**
     * Delete an user-level runner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserRunnerTest() throws Exception {
        String runnerId = null;
        api.deleteUserRunner(runnerId);

        // TODO: test validations
    }
    
    /**
     * Delete a secret in a user scope
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserSecretTest() throws Exception {
        String secretname = null;
        api.deleteUserSecret(secretname);

        // TODO: test validations
    }
    
    /**
     * Delete a user-level variable which is created by current doer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserVariableTest() throws Exception {
        String variablename = null;
        api.deleteUserVariable(variablename);

        // TODO: test validations
    }
    
    /**
     * Get an user-level runner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserRunnerTest() throws Exception {
        String runnerId = null;
        api.getUserRunner(runnerId);

        // TODO: test validations
    }
    
    /**
     * Get user-level runners
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserRunnersTest() throws Exception {
        api.getUserRunners();

        // TODO: test validations
    }
    
    /**
     * Get user settings
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserSettingsTest() throws Exception {
        List<UserSettings> response = api.getUserSettings();

        // TODO: test validations
    }
    
    /**
     * Get a user-level variable which is created by current doer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserVariableTest() throws Exception {
        String variablename = null;
        ActionVariable response = api.getUserVariable(variablename);

        // TODO: test validations
    }
    
    /**
     * Get the user-level list of variables which is created by current doer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserVariablesListTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<ActionVariable> response = api.getUserVariablesList(page, limit);

        // TODO: test validations
    }
    
    /**
     * Get workflow jobs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserWorkflowJobsTest() throws Exception {
        String status = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowJobsResponse response = api.getUserWorkflowJobs(status, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get workflow runs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserWorkflowRunsTest() throws Exception {
        String event = null;
        String branch = null;
        String status = null;
        String actor = null;
        String headSha = null;
        Integer page = null;
        Integer limit = null;
        ActionWorkflowRunsResponse response = api.getUserWorkflowRuns(event, branch, status, actor, headSha, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get a Token to verify
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getVerificationTokenTest() throws Exception {
        String response = api.getVerificationToken();

        // TODO: test validations
    }
    
    /**
     * Create or Update a secret value in a user scope
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUserSecretTest() throws Exception {
        String secretname = null;
        CreateOrUpdateSecretOption body = null;
        api.updateUserSecret(secretname, body);

        // TODO: test validations
    }
    
    /**
     * Update user settings
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUserSettingsTest() throws Exception {
        UserSettingsOptions body = null;
        List<UserSettings> response = api.updateUserSettings(body);

        // TODO: test validations
    }
    
    /**
     * Update a user-level variable which is created by current doer
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUserVariableTest() throws Exception {
        String variablename = null;
        UpdateVariableOption body = null;
        api.updateUserVariable(variablename, body);

        // TODO: test validations
    }
    
    /**
     * Add email addresses
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userAddEmailTest() throws Exception {
        CreateEmailOption body = null;
        List<Email> response = api.userAddEmail(body);

        // TODO: test validations
    }
    
    /**
     * Block a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userBlockUserTest() throws Exception {
        String username = null;
        String note = null;
        api.userBlockUser(username, note);

        // TODO: test validations
    }
    
    /**
     * Check if one user is following another user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCheckFollowingTest() throws Exception {
        String username = null;
        String target = null;
        api.userCheckFollowing(username, target);

        // TODO: test validations
    }
    
    /**
     * Check if a user is blocked by the authenticated user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCheckUserBlockTest() throws Exception {
        String username = null;
        api.userCheckUserBlock(username);

        // TODO: test validations
    }
    
    /**
     * Create a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCreateHookTest() throws Exception {
        CreateHookOption body = null;
        Hook response = api.userCreateHook(body);

        // TODO: test validations
    }
    
    /**
     * creates a new OAuth2 application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCreateOAuth2ApplicationTest() throws Exception {
        CreateOAuth2ApplicationOptions body = null;
        OAuth2Application response = api.userCreateOAuth2Application(body);

        // TODO: test validations
    }
    
    /**
     * Get an user&#39;s actions runner registration token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCreateRunnerRegistrationTokenTest() throws Exception {
        api.userCreateRunnerRegistrationToken();

        // TODO: test validations
    }
    
    /**
     * Create an access token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCreateTokenTest() throws Exception {
        String username = null;
        CreateAccessTokenOption body = null;
        AccessToken response = api.userCreateToken(username, body);

        // TODO: test validations
    }
    
    /**
     * Check whether a user is followed by the authenticated user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentCheckFollowingTest() throws Exception {
        String username = null;
        api.userCurrentCheckFollowing(username);

        // TODO: test validations
    }
    
    /**
     * Whether the authenticated is starring the repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentCheckStarringTest() throws Exception {
        String owner = null;
        String repo = null;
        api.userCurrentCheckStarring(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Unfollow a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentDeleteFollowTest() throws Exception {
        String username = null;
        api.userCurrentDeleteFollow(username);

        // TODO: test validations
    }
    
    /**
     * Remove a GPG key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentDeleteGPGKeyTest() throws Exception {
        Long id = null;
        api.userCurrentDeleteGPGKey(id);

        // TODO: test validations
    }
    
    /**
     * Delete a public key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentDeleteKeyTest() throws Exception {
        Long id = null;
        api.userCurrentDeleteKey(id);

        // TODO: test validations
    }
    
    /**
     * Unstar the given repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentDeleteStarTest() throws Exception {
        String owner = null;
        String repo = null;
        api.userCurrentDeleteStar(owner, repo);

        // TODO: test validations
    }
    
    /**
     * Get a GPG key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentGetGPGKeyTest() throws Exception {
        Long id = null;
        GPGKey response = api.userCurrentGetGPGKey(id);

        // TODO: test validations
    }
    
    /**
     * Get a public key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentGetKeyTest() throws Exception {
        Long id = null;
        PublicKey response = api.userCurrentGetKey(id);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s followers
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListFollowersTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<User> response = api.userCurrentListFollowers(page, limit);

        // TODO: test validations
    }
    
    /**
     * List the users that the authenticated user is following
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListFollowingTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<User> response = api.userCurrentListFollowing(page, limit);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s GPG keys
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListGPGKeysTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<GPGKey> response = api.userCurrentListGPGKeys(page, limit);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s public keys
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListKeysTest() throws Exception {
        String fingerprint = null;
        Integer page = null;
        Integer limit = null;
        List<PublicKey> response = api.userCurrentListKeys(fingerprint, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the repos that the authenticated user owns
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListReposTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.userCurrentListRepos(page, limit);

        // TODO: test validations
    }
    
    /**
     * The repos that the authenticated user has starred
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListStarredTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.userCurrentListStarred(page, limit);

        // TODO: test validations
    }
    
    /**
     * List repositories watched by the authenticated user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentListSubscriptionsTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.userCurrentListSubscriptions(page, limit);

        // TODO: test validations
    }
    
    /**
     * Create a GPG key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentPostGPGKeyTest() throws Exception {
        CreateGPGKeyOption form = null;
        GPGKey response = api.userCurrentPostGPGKey(form);

        // TODO: test validations
    }
    
    /**
     * Create a public key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentPostKeyTest() throws Exception {
        CreateKeyOption body = null;
        PublicKey response = api.userCurrentPostKey(body);

        // TODO: test validations
    }
    
    /**
     * Follow a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentPutFollowTest() throws Exception {
        String username = null;
        api.userCurrentPutFollow(username);

        // TODO: test validations
    }
    
    /**
     * Star the given repo
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentPutStarTest() throws Exception {
        String owner = null;
        String repo = null;
        api.userCurrentPutStar(owner, repo);

        // TODO: test validations
    }
    
    /**
     * List the current user&#39;s tracked times
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userCurrentTrackedTimesTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        List<TrackedTime> response = api.userCurrentTrackedTimes(page, limit, since, before);

        // TODO: test validations
    }
    
    /**
     * delete an access token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userDeleteAccessTokenTest() throws Exception {
        String username = null;
        String token = null;
        api.userDeleteAccessToken(username, token);

        // TODO: test validations
    }
    
    /**
     * Delete Avatar
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userDeleteAvatarTest() throws Exception {
        api.userDeleteAvatar();

        // TODO: test validations
    }
    
    /**
     * Delete email addresses
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userDeleteEmailTest() throws Exception {
        DeleteEmailOption body = null;
        api.userDeleteEmail(body);

        // TODO: test validations
    }
    
    /**
     * Delete a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userDeleteHookTest() throws Exception {
        Long id = null;
        api.userDeleteHook(id);

        // TODO: test validations
    }
    
    /**
     * delete an OAuth2 Application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userDeleteOAuth2ApplicationTest() throws Exception {
        Long id = null;
        api.userDeleteOAuth2Application(id);

        // TODO: test validations
    }
    
    /**
     * Update a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userEditHookTest() throws Exception {
        Long id = null;
        EditHookOption body = null;
        Hook response = api.userEditHook(id, body);

        // TODO: test validations
    }
    
    /**
     * Get a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetTest() throws Exception {
        String username = null;
        User response = api.userGet(username);

        // TODO: test validations
    }
    
    /**
     * Get the authenticated user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetCurrentTest() throws Exception {
        User response = api.userGetCurrent();

        // TODO: test validations
    }
    
    /**
     * Get a user&#39;s heatmap
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetHeatmapDataTest() throws Exception {
        String username = null;
        List<UserHeatmapData> response = api.userGetHeatmapData(username);

        // TODO: test validations
    }
    
    /**
     * Get a hook
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetHookTest() throws Exception {
        Long id = null;
        Hook response = api.userGetHook(id);

        // TODO: test validations
    }
    
    /**
     * get an OAuth2 Application
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetOAuth2ApplicationTest() throws Exception {
        Long id = null;
        OAuth2Application response = api.userGetOAuth2Application(id);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s oauth2 applications
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetOauth2ApplicationTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<OAuth2Application> response = api.userGetOauth2Application(page, limit);

        // TODO: test validations
    }
    
    /**
     * Get an user&#39;s actions runner registration token
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetRunnerRegistrationTokenTest() throws Exception {
        api.userGetRunnerRegistrationToken();

        // TODO: test validations
    }
    
    /**
     * Get list of all existing stopwatches
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetStopWatchesTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<StopWatch> response = api.userGetStopWatches(page, limit);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s access tokens
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userGetTokensTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<AccessToken> response = api.userGetTokens(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * List a user&#39;s activity feeds
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListActivityFeedsTest() throws Exception {
        String username = null;
        Boolean onlyPerformedBy = null;
        LocalDate date = null;
        Integer page = null;
        Integer limit = null;
        List<Activity> response = api.userListActivityFeeds(username, onlyPerformedBy, date, page, limit);

        // TODO: test validations
    }
    
    /**
     * List users blocked by the authenticated user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListBlocksTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<User> response = api.userListBlocks(page, limit);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s email addresses
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListEmailsTest() throws Exception {
        List<Email> response = api.userListEmails();

        // TODO: test validations
    }
    
    /**
     * List the given user&#39;s followers
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListFollowersTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.userListFollowers(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the users that the given user is following
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListFollowingTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.userListFollowing(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the given user&#39;s GPG keys
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListGPGKeysTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<GPGKey> response = api.userListGPGKeys(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the authenticated user&#39;s webhooks
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListHooksTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Hook> response = api.userListHooks(page, limit);

        // TODO: test validations
    }
    
    /**
     * List the given user&#39;s public keys
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListKeysTest() throws Exception {
        String username = null;
        String fingerprint = null;
        Integer page = null;
        Integer limit = null;
        List<PublicKey> response = api.userListKeys(username, fingerprint, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the repos owned by the given user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListReposTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.userListRepos(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * The repos that the given user has starred
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListStarredTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.userListStarred(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * List the repositories watched by a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListSubscriptionsTest() throws Exception {
        String username = null;
        Integer page = null;
        Integer limit = null;
        List<Repository> response = api.userListSubscriptions(username, page, limit);

        // TODO: test validations
    }
    
    /**
     * List all the teams a user belongs to
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userListTeamsTest() throws Exception {
        Integer page = null;
        Integer limit = null;
        List<Team> response = api.userListTeams(page, limit);

        // TODO: test validations
    }
    
    /**
     * Search for users
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userSearchTest() throws Exception {
        String q = null;
        Long uid = null;
        Integer page = null;
        Integer limit = null;
        InlineResponse2001 response = api.userSearch(q, uid, page, limit);

        // TODO: test validations
    }
    
    /**
     * Unblock a user
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userUnblockUserTest() throws Exception {
        String username = null;
        api.userUnblockUser(username);

        // TODO: test validations
    }
    
    /**
     * Update Avatar
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userUpdateAvatarTest() throws Exception {
        UpdateUserAvatarOption body = null;
        api.userUpdateAvatar(body);

        // TODO: test validations
    }
    
    /**
     * update an OAuth2 Application, this includes regenerating the client secret
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userUpdateOAuth2ApplicationTest() throws Exception {
        Long id = null;
        CreateOAuth2ApplicationOptions body = null;
        OAuth2Application response = api.userUpdateOAuth2Application(id, body);

        // TODO: test validations
    }
    
    /**
     * Verify a GPG key
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userVerifyGPGKeyTest() throws Exception {
        GPGKey response = api.userVerifyGPGKey();

        // TODO: test validations
    }
    
}
